### ISSUE TITLE
[Q] Should "batch mode" for STRTCPSVR be based on interactiveness?

### ISSUE THREAD

**Issue by ThePrez** [ThePrez/ServiceCommander-IBMi#115]
See #109 for background. 
(the below text copied from [this comment](https://github.com/ThePrez/ServiceCommander-IBMi/pull/109#issuecomment-1043808725))

I think the solution still has room for improvement. The intent of this check:
```C
is_batch = (pd->pw_name[0] == 'Q');
```
... Is to allow for the `sc` output to be shown to the user when running interactive, but for it to go "batch mode" when run in the IPL or other "headless" environments. 

Brainstorming, do you think it'd be worth checking if we're in a "headless" (non-5250-interactive) mode by calling one of:
- `QsnRtvMod()` (if error, do batch mode)
- Job type from `QUSRJOBI()` (if not 'I', do batch mode)

Adding @chrjorgensen to follow the discussion here

**Comment by chrjorgensen** [comment]
Jesse, I couldn't figure out the reasoning behind the difference between Q-profiles and non-Q-profiles, but your explanation above makes sense.

I think testing for batch mode is the right solution. This gives the user the option to have the output presented by running it interactively - and if any lock was caused by another job running the same STRTCPSVR command, it would be more obvious to the user. Most locks would probably be quite short in this situation anyway, since the system is fully up and not CPU constraint like during or right after IPL - which was my situation.

**Comment by ThePrez** [comment]
> 

Those are really great points. Thank you! Since I landed #116 with your blessing, I'll close this one out (feel free to request a reopen if there's still a missing piece)
