### ISSUE TITLE
[FEATURE-REQUEST]Add install of PostgreSQL

### ISSUE THREAD

**Issue by chrjorgensen** [ThePrez/ServiceCommander-IBMi#142]
**Describe the solution you'd like**

The current script `sc_install_default` does not install a configuration file for PostgreSQL, even though it has been installed on the system.

The PR #140 adds this to the script. It also updates the PostgreSQL configuration to reflect the documentation on [IBM i OSS PostgreSQL install guide](https://ibmi-oss-docs.readthedocs.io/en/latest/postgresql.html).

**Describe alternatives you've considered**

**Additional context**

**Comment by ThePrez** [comment]
Thanks for zeroing in on this topic! 

I have been waffling on the best action plan for PostgreSQL, primarily because the `POSTGRES` user profile needs to be chosen and manually created by the user in order to set up. The user profile doesn't need to be `POSTGRES`. 

The fear is that it would cause confusion if they installed PostgreSQL with a different user profile (`PG_USER` or something) and the `sc` management fails. For that reason, I chose to just have the Postgres config around as an example. 

However, since [our doc](https://ibmi-oss-docs.readthedocs.io/en/latest/postgresql.html) prescribes a `POSTGRES` user profile, I maybe worrying a bit much. 

I think there are three options for resolution here, regarding the deployment of the postgres.yaml file:
1. Leave as-is. Hope people find the example if needed
2. Install the installation by default (as in this PR) and also emphasize the uid issue in the README
3. Install the installation by default, and also add code in `sc` to issue a warning if there is a `sbmjob_opts` containing a `USER(____)` for a non-existent user profile. In the postgres case, I assume the odds of another user named `POSTGRES` is very low

@chrjorgensen , what is your vote?

**Comment by ThePrez** [comment]
It's relevant to this issue, so putting here.... 

I forgot to address your question (sorry!) at https://github.com/ThePrez/ServiceCommander-IBMi/pull/134#issuecomment-1075735792
 > One question then: How do you manage any user changes to the configs? That they are not overwritten in future updates of Service Commander? Or do the users have to copy the config files to another directory to keep their changes - a directory that Service Commander will read before its own "oss-common" directory?
 
We define these config files as `%config(noreplace)` in the `.spec` file, here: https://github.com/ThePrez/ServiceCommander-IBMi/blob/cdc136871feabfb10e9d22fe31f843462db11d7a/service-commander.spec#L68

With this behavior, the RPM processing will not replace any user-modified configuration files. So if they modify one of the preinstalled services, their modifications will remain intact with reinstalls/upgrades of `service-commander`
Note, however, that "niceness" doesn't apply if you do a `make install` on your local machine! (maybe we should think about that corner case...)

**Comment by chrjorgensen** [comment]
Nice - thanks for your answer!

Excuse my curiosity combined with some lack of knowledge, but will it be possible for a user to reset a specific config, that once was altered by the user but he/she now wants the (new) default?

Just thinking of a situation I could easily bring myself into in the future - with all my tweaking and testing as a system administrator I often start from scratch by resetting a config to the defaults... 😂

**Comment by ThePrez** [comment]
> Excuse my curiosity combined with some lack of knowledge, but will it be possible for a user to reset a specific config, that once was altered by the user but he/she now wants the (new) default?

I believe they can delete the file and then reinstall the RPM, though it might be good to have a tool to do this more explicitly

> Just thinking of a situation I could easily bring myself into in the future - with all my tweaking and testing as a system administrator I often start from scratch by resetting a config to the defaults..

That being said, some form of snapshot/restore commands would probably be a good thing to have!

**Comment by ThePrez** [comment]
I've opened #149 and #150 to track ideas from the previous comment. 

With the merging of #140, I think we can close this out. @chrjorgensen please reopen if I missed anything. Thanks!
