### ISSUE TITLE
[BUG]ENDTCPSVR *ALL ends with error in terminal session

### ISSUE THREAD

**Issue by chrjorgensen** [ThePrez/ServiceCommander-IBMi#174]
**Describe the bug**

When STRTCPSVR integration and system service definitions are installed, ending the system (e.g. when using GO SAVE option 21 for doing system backup) will end in terminal session with error for service `system_as-sts`:

![billede](https://user-images.githubusercontent.com/13275072/171717021-94827eea-b875-466b-a67e-d94a5d97071e.png)

This prohibits scheduled system backups using GO SAVE 21 and other commands ending all TCP/IP services.

**To Reproduce**

See above...

**Expected behavior**

Service Commander should not end the system services, when all TCP/IP servers are ended - IBM i will end or has already ended the system services!

**Verbose output**
Run the command with the `-v` option and share the output here.

**Additional context**

**Comment by ThePrez** [comment]
PR #175 addresses the usage of `-a`, but also, the "Unable to determine job" error should not be a fatal error. It should have given the error but proceeded to stop the others. 
Or is it working correctly in that regard, but the mere presence of terminal output is interfering with the SAVE operation?


Am I correct to assume you're using the latest version of sc?

**Comment by ThePrez** [comment]
I misremembered the code logic. As written, it pretty explicitly stops if any single requested service fails. See the logic here: 
https://github.com/ThePrez/ServiceCommander-IBMi/blob/68d35a7b00d5b6b9f96db824a1b4c088a17f4194/src/main/java/jesseg/ibmi/opensource/ServiceCommander.java#L307

I wonder if we should indeed be more tolerant here. "Ope, we failed to stop this one, but we'll try the others"

I'm guessing the `SAVE` operation fails because we end up exiting with a nonzero exit code here: https://github.com/ThePrez/ServiceCommander-IBMi/blob/68d35a7b00d5b6b9f96db824a1b4c088a17f4194/src/main/java/jesseg/ibmi/opensource/ServiceCommander.java#L302

Of course, maybe that's ok. If we're trying to stop all the servers and one isn't stopped, maybe we _should_ hold up the save (?)

**Comment by chrjorgensen** [comment]
IMHO I think it's okay to end with a failure when a service can't be stopped - to show the user that something is not configured correctly. In PR #175 we remove the `-a` option when the system is ending TCP/IP, so the case above would not happen again - and the error message will only appear if the user has made the error.

It's always difficult to determine how much one should protect the user from... the user! 😆
