### ISSUE TITLE
[FEATURE-REQUEST] `start` and `restart` should act similarly

### ISSUE THREAD

**Issue by worksofliam** [ThePrez/ServiceCommander-IBMi#215]
<img width="565" alt="image" src="https://user-images.githubusercontent.com/3708366/236325444-50c7581f-52f8-495e-abf4-60826c723d02.png">

**Comment by chrjorgensen** [comment]
@worksofliam I don't agree on this request - I see a clear difference between starting a service and restarting it!

Unlike an app, a service can serve multiple users and connections, not just one user. If `start` acted like `restart` and ended the service before starting it again, it could break active user sessions.

If you want to start your app and have it end an already running instance first, just use `restart` instead of `start`, as @ThePrez suggests:

![image](https://user-images.githubusercontent.com/13275072/236339158-a7032cd7-9ad9-448d-b449-1589f1876a37.png)

**Comment by worksofliam** [comment]
@chrjorgensen 

> If you want to start your app and have it end an already running instance first, just use restart instead of start, as @ThePrez suggests:

That makes complete sense. Thank you!
